# Generated by Django 6.0.5 on 2026-05-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('paragraph_count', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('lexical_density', models.FloatField(default=0)),
                ('avg_sentence_length', models.FloatField(default=0)),
                ('avg_word_length', models.FloatField(default=0)),
                ('estimated_read_min', models.IntegerField(default=0)),
                ('passive_voice_count', models.IntegerField(default=0)),
                ('long_sentences', models.IntegerField(default=0)),
                ('top_words_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='editor.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
