# Generated by Django 6.0.5 on 2026-05-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_inbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='notes.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='notes.note')),
                ('to_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='notes.note')),
            ],
            options={
                'unique_together': {('from_note', 'to_note')},
            },
        ),
    ]
